SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true

GROUP=de.musichin.ktxml

POM_PACKAGING=jar

POM_NAME=ktXML
POM_DESCRIPTION=Simple XML processing library with immutable data objects.

POM_URL=https://github.com/musichin/ktXML
POM_SCM_URL=https://github.com/musichin/ktXML/
POM_SCM_CONNECTION=scm:git:git://github.com/musichin/ktXML.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/musichin/ktXML.git

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=musichin
POM_DEVELOPER_NAME=Anton Musichin
